blueprint:
  name: deCONZ - icasa PULSE 8S keypad
  description: |
    Control anything using icasa Pulse 8S keypad

  domain: automation
  input:
    remote:
      name: Keypad
      description: Keypad to use
      selector:
        device:
          integration: deconz
          manufacturer: icasa
    button_on:
      name: On Button
      description: Action to run on press on On button
      default: []
      selector:
        action:
    button_on_long:
      name: On Long Press
      description: Action to run on press on On long button
      default: []
      selector:
        action:
    button_off:
      name: Off Button
      description: Action to run on press on Off button
      default: []
      selector:
        action:
    button_off_long:
      name: Off Long Press
      description: Action to run on press on Off long button
      default: []
      selector:
        action:
    button_1:
      name: Button S1
      description: Action to run on Button S1
      default: []
      selector:
        action:
    button_2:
      name: Button S2
      description: Action to run on Button S2
      default: []
      selector:
        action:
    button_3:
      name: Button S3
      description: Action to run on Button S3
      default: []
      selector:
        action:
    button_4:
      name: Button S4
      description: Action to run on Button S4
      default: []
      selector:
        action:
    button_5:
      name: Button S5
      description: Action to run on Button S5
      default: []
      selector:
        action:
    button_6:
      name: Button S6
      description: Action to run on Button S6
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      device_id: !input "remote"

action:
  - variables:
      event: "{{ trigger.event.data.event }}"
  - choose:
      - conditions:
          - "{{ event == 1001 }}"
        sequence: !input button_off_long
      - conditions:
          - "{{ event == 1002 }}"
        sequence: !input button_off
      - conditions:
          - "{{ event == 2001 }}"
        sequence: !input button_on_long
      - conditions:
          - "{{ event == 2002 }}"
        sequence: !input button_on
      - conditions:
          - "{{ event == 3002 }}"
        sequence: !input button_1
      - conditions:
          - "{{ event == 4002 }}"
        sequence: !input button_2
      - conditions:
          - "{{ event == 5002 }}"
        sequence: !input button_3
      - conditions:
          - "{{ event == 6002 }}"
        sequence: !input button_4
      - conditions:
          - "{{ event == 7002 }}"
        sequence: !input button_5
      - conditions:
          - "{{ event == 8002 }}"
        sequence: !input button_6
