blueprint:
  name: Last person leaving a zone with windows left open
  description: Regularly test all sensors with 'opening' device-class for state open
  domain: automation
  input:
    exclude:
      name: Excluded Sensors
      description: Opening sensors to exclude from detection. Only entities are supported, devices must be expanded!
      default: {entity_id: []}
      selector:
        target:
          entity:
            device_class: opening
    door_sensor:
      name: Main Door
      description: The door that is opened when starting the notification.
      selector:
        entity:
          domain: opening
    leaving_zone:
      name: Leaving Zone
      description: The zone that that the last person is leaving through the opened door.
      selector:
        entity:
          domain: zone
    actions:
      name: Actions
      description: Notifications or similar to be run. {{sensors}} is replaced with
        the names of sensors being open.
      selector:
        action: {}
variables:
  exclude: !input 'exclude'
  sensors: >-
    {% set result = namespace(sensors=[]) %}
    {% for state in states.sensor | selectattr('attributes.device_class', '==', 'opening') %}
      {% if "on" == state.state and not state.entity_id in exclude.entity_id %}
        {% set result.sensors = result.sensors + [state.name ~ ' (' ~ state.state ~ ' %)'] %}
      {% endif %}
    {% endfor %}
    {% for state in states.binary_sensor | selectattr('attributes.device_class', '==', 'opening') | selectattr('state', '==', 'on') %}
      {% if not state.entity_id in exclude.entity_id %}
        {% set result.sensors = result.sensors + [state.name] %}
      {% endif %}
    {% endfor %}
    {{result.sensors|join(', ')}}
trigger:
  platform: state
  entity_id: !input door_sensor
condition:
- '{{ sensors != '''' }}'
- condition: numeric_state
  entity_id: !input 'leaving_zone'
  below: '2'
action:
- choose: []
  default: !input 'actions'
mode: single
